name: Release Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package
      - name: Update Patch Version
        run: |
          mvn --batch-mode --no-transfer-progress build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT \
          versions:commit

      - name: Perform Release Build
        run: |
          git config user.name Changolaxtra
          git config user.email dan.rojasx@gmail.com
          mvn --batch-mode --no-transfer-progress release:clean release:prepare release:perform \
          -Darguments="-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true" \
          -Dusername=s-airchangeservice -Dpassword=${{ secrets.SSH_PRIVATE_KEY }}
